name: pipeline
on: 
  push:

jobs:
  build:
    name: Build Archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build with maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: target/
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
            name: artifact
            path: ./target/demo-0.0.2.7-SNAPSHOT.jar
  deploy-stg:
    runs-on: ubuntu-latest
    environment: 
      name: stg
    needs: build

    if: github.ref == 'refs/heads/develop'
    steps: 
      - name: Deploy
        shell: bash
        run: | 
          echo "Deploy stg"

  deploy-pre:
    runs-on: ubuntu-latest
    environment: 
      name: pre
    needs: build

    if: github.ref == 'refs/heads/release'
    steps: 
      - name: Deploy
        shell: bash
        run: | 
          echo "Deploy Pre"

  deploy-prod:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    needs: build

    if: github.ref == 'refs/heads/main'
    steps: 
      - name: Deploy
        shell: bash
        run: | 
          echo "Deploy PROD"


  # deploy-aws:
  #   needs: build
  #   name: Deploy aws
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download JAR
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: artifact
  #         path: target/
  #     - name: Display structure of downloaded files
  #       run: ls -R
  #     - name: Deploy to EB
  #       uses: einaregilsson/beanstalk-deploy@v21
  #       with:
  #         aws_access+key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
  #         wait_for_environment_recovery: 90
  #         use_existing_version_if_available: true
  #         application_name: Teste1
  #         environment_name: Teste1-env
  #         version_label: ${{ github.SHA }}
  #         region: us-east-1
  #         deploy_package: ./tagrte/demo-0.0.2.7-SNAPSHOT.jar
      
    

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0
  #   - uses: actions/setup-java@v3
  #     with:
  #       java-version: '11'
  #       distribution: 'adopt'
  #       package: '*.jar'
  #   - name: Publish package
  #     run: mvn --batch-mode deploy
  #     env:
  #       GITHUN_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
      
      
