name: pipeline
on: 
  push:

jobs:
  build:
    name: Build Archive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build with maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: target/
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
            name: artifact
            path: ./target/demo-0.0.2.7-SNAPSHOT.jar
  deploy-stg:
    runs-on: ubuntu-latest
    environment: 
      name: stg
    needs: build

    if: github.ref == 'refs/heads/develop'
    steps: 
      - name: Deploy
        shell: bash
        run: | 
          echo "Deploy stg"

  deploy-pre:
    runs-on: ubuntu-latest
    environment: 
      name: pre
    needs: build

    if: github.ref == 'refs/heads/release'
    steps: 
      - name: Deploy
        shell: bash
        run: | 
          echo "Deploy Pre"

  deploy-prod:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    needs: build

    if: github.ref == 'refs/heads/main'
    steps: 
      - name: Deploy
        shell: bash
        run: | 
          echo "Deploy PROD"
    

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     contents: read
  #     packages: write

  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0
  #   - uses: actions/setup-java@v3
  #     with:
  #       java-version: '11'
  #       distribution: 'adopt'
  #       package: '*.jar'
  #   - name: Publish package
  #     run: mvn --batch-mode deploy
  #     env:
  #       GITHUN_TOKEN: ${{secrets.GITHUB_TOKEN}}
    
      
      
